repos:
- repo: https://github.com/timothycrosley/isort.git
  rev: '4.3.21'
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.761'
  hooks:
  - id: mypy
