FROM osrf/ros:melodic-desktop-full

RUN curl -sSfL https://download.jetbrains.com/cpp/CLion-2019.3.3.tar.gz | tar -xzf - && \
    mv clion-2019.3.3 /opt/clion && \
    ln -s /opt/clion/bin/clion.sh /usr/bin/clion
